# Generated by Django 3.2.16 on 2022-10-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
